version: '3.8'

services:
  bot:
    build: 
      context: ./bot
      dockerfile: dockerfile
    container_name: bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bruno
      - DB_USER=bruno
      - DB_PASSWORD=1234
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  app:
    build:
      context: ./pars
      dockerfile: dockerfile
    container_name: app_service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bruno
      - DB_USER=bruno
      - DB_PASSWORD=1234
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=bruno
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bruno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
